// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnVw6ffCPlu94LarljatnjD6jQwXiLXjs',
    appId: '1:1783737815:web:f29a0c8a02ea5255ebef92',
    messagingSenderId: '1783737815',
    projectId: 'yadou-app',
    authDomain: 'yadou-app.firebaseapp.com',
    storageBucket: 'yadou-app.firebasestorage.app',
    measurementId: 'G-4LJXPJPPQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjrdaGyjuh96E5WdI8MQ07izLv1oOxnZ8',
    appId: '1:1783737815:android:ebea0fa440093bedebef92',
    messagingSenderId: '1783737815',
    projectId: 'yadou-app',
    storageBucket: 'yadou-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9YdL49RwdG49iQJVv1zu_EW6gL4DlzTg',
    appId: '1:1783737815:ios:38b742f181e42234ebef92',
    messagingSenderId: '1783737815',
    projectId: 'yadou-app',
    storageBucket: 'yadou-app.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );
}
